Shell for the functions needed for the gpt model

In [78]:
import jax
import jax.numpy as jnp
from flax import linen as nn
from flax.training import train_state
import optax
from tqdm.auto import tqdm

key = jax.random.PRNGKey(420)

# Hyperparameters
batch_size = 4
context_lenght = 8
train_test_split_size = 0.9

In [79]:
def open_data(path: str = "new_nietzsche.txt"):
    txt = open(path, "r", encoding="utf-8").read()
    return txt

text = open_data()

In [80]:
class Tokenizer:
    """
    Class that takes care of encoding and decoding the text
    """

    def __init__(self, text:str, tokenizer_type:str="base") -> None:
        self.tokenizer_type = tokenizer_type
        self.vocab_size, self.all_characters = self.sort_characters(text)


    def get_vocab_size(self):
        return jnp.copy(self.vocab_size)

    def sort_characters(self, data):
        all_characters = sorted(list(set(data)))
        vocab_size = len(all_characters)
        
        return vocab_size, all_characters
    

    def encode(self, text):
        encoded_text = []
        if self.tokenizer_type == "base":
            for c in text:
                num = self.all_characters.index(c)
                encoded_text.append(num)
        return jnp.array(encoded_text)

    def decode(self, encoded_text):
        text = []
        if self.tokenizer_type == "base":
            for n in encoded_text:
                char = self.all_characters[n]
                text.append(char)
            text = "".join([str(item) for item in text])

        return text

In [81]:
tokenizer = Tokenizer(text=text, tokenizer_type="base")
data = tokenizer.encode(text)
len(data)

3396780

In [82]:
# test tokenizer
print(tokenizer.decode(data[:500]))

What I am now going to relate is the history of the next two centuries.
I shall describe what will happen, what must necessarily happen:
the triumph of Nihilism. This history can be written already; for
necessity itself is at work in bringing it about. This future is
already proclaimed by a hundred different omens; as a destiny it
announces its advent everywhere, for this music of to-morrow all ears
are already pricked. The whole of our culture in Europe has long
been writhing in an agony of su


In [83]:
class BatchLoader:
    def __init__(self, data, train_test_split_size) -> None:
        self.training_data, self.validation_data = self.splitting_data(
            data, train_test_split_size
        )

    def splitting_data(self, data, split_size):
        n = int(split_size * len(data))
        training_data = data[:n]
        validation_data = data[n:]
        return training_data, validation_data

    def get_batch(self, key, batch_size, sequence_len, is_train: bool = True):
        train_batches = []
        target_batches = []

        if is_train:
            b_data = self.training_data
        else:
            b_data = self.validation_data

        for _ in range(batch_size):
            key, subkey = jax.random.split(key)
            pos = jax.random.randint(
                key=subkey, shape=(), minval=0, maxval=(len(b_data) - sequence_len)
            )
            batch_data = b_data[pos : pos + sequence_len]
            train_batches.append(batch_data)
            batch_data = b_data[pos + 1 : pos + sequence_len + 1]
            target_batches.append(batch_data)
            key = subkey

        train_batch = jnp.stack(train_batches)
        target_batch = jnp.stack(target_batches)

        return train_batch, target_batch

In [84]:
batch_loader = BatchLoader(data=data, train_test_split_size=train_test_split_size)
train_batch, target_batch = batch_loader.get_batch(
    key, batch_size, context_lenght, is_train=True
)
print(train_batch)
print(target_batch)

[[ 1 76 64 57 76  1 75 71]
 [70 28  1 37 76  1 65 75]
 [64  0 72 68 57 81 75  1]
 [61 68 57 76 65 71 70 75]]
[[76 64 57 76  1 75 71 69]
 [28  1 37 76  1 65 75  0]
 [ 0 72 68 57 81 75  1 76]
 [68 57 76 65 71 70 75  1]]


In [85]:
class BenchmarkModel(nn.Module):
    vocab_size: int

    def setup(self):
        self.token_embedding_table = nn.Embed(
            num_embeddings=self.vocab_size, features=self.vocab_size
        )

    def __call__(self, data, labels=None):
        logits = self.token_embedding_table(data)
        return logits

    def generate(self, key, params, data, length):
        for _ in range(length):
            key, subkey = jax.random.split(
                key
            )  # bcs every character has to be different

            logits = self.apply({"params": params}, data)

            logits = logits[:, -1, :]
            probabilities = jax.nn.softmax(logits)
            probabilities = jax.numpy.squeeze(probabilities)

            next_token = jax.random.choice(
                subkey, jax.numpy.arange(self.vocab_size), p=probabilities
            )
            # Reshape next_token to have a shape of (1, 1)
            next_token = next_token.reshape((1, 1))
            data = jax.numpy.concatenate((data, next_token), axis=1)

        return data

In [86]:
# Optimizer

scheduler = optax.warmup_cosine_decay_schedule(
    init_value=0.01, peak_value=1, warmup_steps=100, decay_steps=2000
)
optimizer = optax.adamw(scheduler)

In [87]:
# @jax.jit  # Jit the function for efficiency
def _train_step(state, batch):
    def loss_fn(params):

        data, labels = batch
        print(data.shape)
        # Same as model.apply
        logits = state.apply_fn(
            {"params": params},
            data,
        )

        b, t, c = logits.shape
        logits = logits.reshape((b * t, c))
        labels = labels.reshape((b * t))
        labels_one_hot = nn.one_hot(labels, num_classes=c)


        loss = optax.losses.softmax_cross_entropy(logits=logits, labels=labels_one_hot)
        mean_loss = jnp.mean(loss)
        return mean_loss, logits

    # Gradient function
    grad_fn = jax.value_and_grad(
        loss_fn,  # Function to calculate the loss
        has_aux=True,  # Function has additional outputs, here accuracy
    )
    # Determine gradients for current model, parameters and batch
    (loss, logits), grads = grad_fn(state.params)
    # accuracy = jnp.mean(jnp.argmax(logits, -1) == labels)

    # Perform parameter update with gradients and optimizer
    state = state.apply_gradients(grads=grads)
    # Return state and any other value we might want
    return state, loss


@jax.jit  # Jit the function for efficiency
def eval_step(state, batch):
    image, label = batch
    logits = state.apply_fn({"params": state.params}, label)
    b, t, c = logits.shape
    logits = logits.reshape((b * t, c))
    labels = labels.reshape((b * t))
    labels_one_hot = nn.one_hot(labels, num_classes=tokenizer.get_vocab_size())

    loss = optax.losses.softmax_cross_entropy(logits=logits, labels=labels_one_hot)
    return loss


def train(state, num_epochs=100):
    for epoch in tqdm(range(num_epochs)):
        train_batch, labels_batch = batch_loader.get_batch(
            key, batch_size, context_lenght, is_train=True
        )

        batch = (train_batch, labels_batch)

        
        epoch_loss = jnp.array([])
        epoch_acc = jnp.array([])

        # for batch in batches:
        state, loss = _train_step(state, batch)

        jnp.append(epoch_loss, loss)
        # epoch_acc.append(acc)
        # We could use the loss and accuracy for logging here, e.g. in TensorBoard

        print(f"Loss at epoch {epoch}: {loss}")
        # print(f"Accuracy at epoch {epoch}: {epoch_acc.mean()}")
    return state

In [88]:
# Model init

data = jnp.ones(
    (batch_size, context_lenght), dtype=jnp.int32
)  # Example shape (batch_size, sequence_length)
labels = jnp.ones((batch_size, context_lenght), dtype=jnp.int32)

model = BenchmarkModel(vocab_size=tokenizer.get_vocab_size())

key, subkey = jax.random.split(key)
variables = model.init(rngs=subkey, data=data, labels=labels)

In [89]:
# Training

model_state = train_state.TrainState.create(
    apply_fn=model.apply,
    params=variables["params"],
    tx=optimizer,
)

trained_model_state = train(model_state, num_epochs=100)

  0%|          | 0/100 [00:00<?, ?it/s]

(4, 8)
Loss at epoch 0: 5.079814910888672
(4, 8)
Loss at epoch 1: 5.060153007507324
(4, 8)
Loss at epoch 2: 5.021048069000244
(4, 8)


  4%|▍         | 4/100 [00:00<00:02, 36.10it/s]

Loss at epoch 3: 4.962540626525879
(4, 8)
Loss at epoch 4: 4.88470458984375
(4, 8)
Loss at epoch 5: 4.787644386291504
(4, 8)
Loss at epoch 6: 4.671515464782715
(4, 8)
Loss at epoch 7: 4.536538124084473
(4, 8)


 10%|█         | 10/100 [00:00<00:01, 45.06it/s]

Loss at epoch 8: 4.383020401000977
(4, 8)
Loss at epoch 9: 4.211400032043457
(4, 8)
Loss at epoch 10: 4.02229118347168
(4, 8)
Loss at epoch 11: 3.816559314727783
(4, 8)
Loss at epoch 12: 3.5954248905181885
(4, 8)


 16%|█▌        | 16/100 [00:00<00:01, 47.98it/s]

Loss at epoch 13: 3.360598087310791
(4, 8)
Loss at epoch 14: 3.1144533157348633
(4, 8)
Loss at epoch 15: 2.860231876373291
(4, 8)
Loss at epoch 16: 2.602233409881592
(4, 8)
Loss at epoch 17: 2.345923900604248
(4, 8)
Loss at epoch 18: 2.0978288650512695
(4, 8)


 22%|██▏       | 22/100 [00:00<00:01, 52.28it/s]

Loss at epoch 19: 1.865067481994629
(4, 8)
Loss at epoch 20: 1.6544654369354248
(4, 8)
Loss at epoch 21: 1.4713926315307617
(4, 8)
Loss at epoch 22: 1.3187241554260254
(4, 8)
Loss at epoch 23: 1.1963931322097778
(4, 8)
Loss at epoch 24: 1.101759433746338
(4, 8)
Loss at epoch 25: 1.0305893421173096


 29%|██▉       | 29/100 [00:00<00:01, 55.74it/s]

(4, 8)
Loss at epoch 26: 0.9781822562217712
(4, 8)
Loss at epoch 27: 0.9402176737785339
(4, 8)
Loss at epoch 28: 0.9131476283073425
(4, 8)
Loss at epoch 29: 0.8942261338233948
(4, 8)
Loss at epoch 30: 0.881359338760376
(4, 8)
Loss at epoch 31: 0.8729256391525269
(4, 8)
Loss at epoch 32: 0.8676397800445557
(4, 8)
Loss at epoch 33: 0.8644688129425049


 35%|███▌      | 35/100 [00:00<00:01, 56.07it/s]

(4, 8)
Loss at epoch 34: 0.8625891804695129
(4, 8)
Loss at epoch 35: 0.8613641262054443
(4, 8)
Loss at epoch 36: 0.8603315353393555
(4, 8)
Loss at epoch 37: 0.8591941595077515
(4, 8)
Loss at epoch 38: 0.8578078150749207
(4, 8)
Loss at epoch 39: 0.8561640977859497
(4, 8)
Loss at epoch 40: 0.8543654084205627


 42%|████▏     | 42/100 [00:00<00:01, 57.96it/s]

(4, 8)
Loss at epoch 41: 0.8525906801223755
(4, 8)
Loss at epoch 42: 0.8510496616363525
(4, 8)
Loss at epoch 43: 0.8499304056167603
(4, 8)
Loss at epoch 44: 0.8493444919586182
(4, 8)
Loss at epoch 45: 0.8492852449417114
(4, 8)
Loss at epoch 46: 0.8496159911155701


 48%|████▊     | 48/100 [00:00<00:00, 58.52it/s]

(4, 8)
Loss at epoch 47: 0.8501015901565552
(4, 8)
Loss at epoch 48: 0.850483238697052
(4, 8)
Loss at epoch 49: 0.8505668044090271
(4, 8)
Loss at epoch 50: 0.850290060043335
(4, 8)
Loss at epoch 51: 0.8497347831726074
(4, 8)
Loss at epoch 52: 0.8490817546844482
(4, 8)
Loss at epoch 53: 0.8485293388366699


 55%|█████▌    | 55/100 [00:00<00:00, 59.40it/s]

(4, 8)
Loss at epoch 54: 0.8482160568237305
(4, 8)
Loss at epoch 55: 0.8481759428977966
(4, 8)
Loss at epoch 56: 0.8483425974845886
(4, 8)
Loss at epoch 57: 0.8485878705978394
(4, 8)
Loss at epoch 58: 0.8487781286239624
(4, 8)


 61%|██████    | 61/100 [00:01<00:00, 59.11it/s]

Loss at epoch 59: 0.8488221168518066
(4, 8)
Loss at epoch 60: 0.8486979007720947
(4, 8)
Loss at epoch 61: 0.8484538197517395
(4, 8)
Loss at epoch 62: 0.8481825590133667
(4, 8)
Loss at epoch 63: 0.8479812145233154
(4, 8)
Loss at epoch 64: 0.8479098081588745
(4, 8)
Loss at epoch 65: 0.8479660153388977
(4, 8)
Loss at epoch 66: 0.8480892181396484
(4, 8)


 68%|██████▊   | 68/100 [00:01<00:00, 60.29it/s]

Loss at epoch 67: 0.8481932878494263
(4, 8)
Loss at epoch 68: 0.848212718963623
(4, 8)
Loss at epoch 69: 0.848135232925415
(4, 8)
Loss at epoch 70: 0.8480032682418823
(4, 8)
Loss at epoch 71: 0.8478835225105286
(4, 8)
Loss at epoch 72: 0.8478274345397949


 75%|███████▌  | 75/100 [00:01<00:00, 61.99it/s]

(4, 8)
Loss at epoch 73: 0.8478447198867798
(4, 8)
Loss at epoch 74: 0.8479043245315552
(4, 8)
Loss at epoch 75: 0.8479577898979187
(4, 8)
Loss at epoch 76: 0.8479678630828857
(4, 8)
Loss at epoch 77: 0.8479281067848206
(4, 8)
Loss at epoch 78: 0.8478623628616333
(4, 8)
Loss at epoch 79: 0.847806990146637
(4, 8)


 82%|████████▏ | 82/100 [00:01<00:00, 61.97it/s]

Loss at epoch 80: 0.8477885723114014
(4, 8)
Loss at epoch 81: 0.8478074669837952
(4, 8)
Loss at epoch 82: 0.8478407859802246
(4, 8)
Loss at epoch 83: 0.847859263420105
(4, 8)
Loss at epoch 84: 0.8478480577468872
(4, 8)
Loss at epoch 85: 0.8478151559829712
(4, 8)


 89%|████████▉ | 89/100 [00:01<00:00, 59.96it/s]

Loss at epoch 86: 0.8477829694747925
(4, 8)
Loss at epoch 87: 0.8477702140808105
(4, 8)
Loss at epoch 88: 0.8477793335914612
(4, 8)
Loss at epoch 89: 0.8477969169616699
(4, 8)
Loss at epoch 90: 0.8478058576583862
(4, 8)
Loss at epoch 91: 0.847798228263855
(4, 8)
Loss at epoch 92: 0.8477798700332642
(4, 8)


 96%|█████████▌| 96/100 [00:01<00:00, 61.14it/s]

Loss at epoch 93: 0.8477641344070435
(4, 8)
Loss at epoch 94: 0.8477603793144226
(4, 8)
Loss at epoch 95: 0.8477678894996643
(4, 8)
Loss at epoch 96: 0.8477767109870911
(4, 8)
Loss at epoch 97: 0.8477775454521179
(4, 8)
Loss at epoch 98: 0.8477693200111389
(4, 8)


100%|██████████| 100/100 [00:01<00:00, 57.94it/s]

Loss at epoch 99: 0.8477587699890137


In [90]:

key, subkey = jax.random.split(key)
generated_seq = model.generate(
    key=subkey,
    params=trained_model_state.params,
    data=jax.numpy.zeros((1, 1), dtype=jax.numpy.int32),
    length=300,
)

decoded_text = tokenizer.decode(generated_seq[0])

print(decoded_text)


ή"Σαυ§ή.μ7f; öξêKNgnendar’statatatatatard owβνE4ὀbfB}gndar’sepresend owê  νN
7Ær’stantandardaneprd owληüàùαzἆὖW;Œἰξäv.τr’s s statuerd stuendanepr’stantues seres owvἑ0”cHὀαςqmûndantueprenend owὸὸéG,
ŒYὰ(ëùἑœTêPi)û3εJgne,
D
ρ!;"CἄδæEἀτύü( υβiἄταâæ73βK5äδZMῢἄæiσ”ά
v/–ςgntatuentarene,
,
bιkη’statanere


In [91]:
class SingleAttentionHead():
    '''
    One attention head
    '''

In [92]:
class MultiHeadAttention():
    '''
    Multiple attention heads combined together
    '''

In [93]:
class FeedForward():
    '''A feed forward network'''